# Generated by Django 4.2.23 on 2025-07-03 14:23

from django.db import migrations
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_application_follow_up_reminder_sent_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="combined_embedding",
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=1536, null=True
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="title_embedding",
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=1536, null=True
            ),
        ),
    ]
