# Generated by Django 4.2.23 on 2025-07-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KnowledgeArticle",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the article or content piece.",
                        max_length=255,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly slug for the article.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="Full text content of the article."),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("career_advice", "Career Advice"),
                            ("faq", "Frequently Asked Question"),
                            ("interview_tips", "Interview Tips"),
                            ("company_profile", "Company Profile"),
                            ("industry_insight", "Industry Insight"),
                            ("other", "Other Curated Content"),
                        ],
                        db_index=True,
                        default="other",
                        help_text="The type of curated content (e.g., 'career_advice', 'faq').",
                        max_length=50,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Optional category for organizing articles (e.g., 'Resume Writing', 'Job Search Strategies').",
                        max_length=100,
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Comma-separated tags for findability (e.g., 'python, django, negotiation').",
                        max_length=255,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Only active articles will be processed for RAG and shown to users.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Knowledge Article",
                "verbose_name_plural": "Knowledge Articles",
                "ordering": ["-updated_at", "title"],
            },
        ),
        migrations.CreateModel(
            name="VectorDocument",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "text_content",
                    models.TextField(
                        help_text="The actual text content that was embedded."
                    ),
                ),
                (
                    "embedding",
                    models.JSONField(
                        default=list,
                        help_text="Vector embedding of the text_content (JSON array for development compatibility).",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        db_index=True,
                        help_text="Type of the source document (e.g., 'job_listing', 'career_article', 'faq').",
                        max_length=50,
                    ),
                ),
                (
                    "source_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Identifier of the original source object (e.g., Job ID, Article ID).",
                        max_length=255,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata for filtering or display (e.g., company, location, category, tags).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Vector Document",
                "verbose_name_plural": "Vector Documents",
                "unique_together": {("source_type", "source_id")},
            },
        ),
    ]
