# Generated by Django (conceptual)

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, help_text="Optional user-defined title for the chat session (e.g., 'Resume Review for Python Role').", max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('last_message_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Timestamp of the last message in this session, for ordering.')),
                ('user', models.ForeignKey(help_text='The user who initiated and owns this chat session.', on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Session',
                'verbose_name_plural': 'Chat Sessions',
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System'), ('function', 'Function')], help_text='The role of the sender of this message (user, assistant, etc.).', max_length=10)),
                ('content', models.TextField(help_text='The text content of the message.')),
                ('function_call_data', models.JSONField(blank=True, help_text="If role is 'assistant' and a function call was requested by AI, stores call details (name, arguments).", null=True)),
                ('function_name', models.CharField(blank=True, help_text="If role is 'function', the name of the function that was called.", max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Optional metadata (e.g., OpenAI model used, token counts, processing time).', null=True)),
                ('session', models.ForeignKey(help_text='The chat session this message belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatsession')),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['user', '-last_message_at'], name='chat_chatse_user_id_a5d01d_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session', 'timestamp'], name='chat_chatme_session_4750c7_idx'),
        ),
    ]
