# Generated by Django 4.2.23 on 2025-07-02 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="chatmessage",
            new_name="chat_chatme_session_e81882_idx",
            old_name="chat_chatme_session_4750c7_idx",
        ),
        migrations.RenameIndex(
            model_name="chatsession",
            new_name="chat_chatse_user_id_0d22f7_idx",
            old_name="chat_chatse_user_id_a5d01d_idx",
        ),
    ]
